### ISSUE TITLE
migrate all wiki pages

### ISSUE THREAD

**Issue by egonw** [BlueObelisk/blueobelisk.github.io#1]
They currently are given at https://sourceforge.net/p/blueobelisk/bowiki/Main_Page/

**Comment by zmughal** [comment]
I have done a Sourceforge-to-GitHub wiki migration in the past before using this code I wrote <https://github.com/primordial-soup/sourceforge-wiki-export>. I think I can give this a shot.

How do you want to host the wiki pages?

**Comment by zmughal** [comment]
I ran the main script from that:
```shell
./dump-sf-wiki-json blueobelisk bowiki
```
and got the following files. 
[blueobelisk-bowiki.zip](https://github.com/BlueObelisk/blueobelisk.github.io/files/1297214/blueobelisk-bowiki.zip)

**Comment by egonw** [comment]
Thanks! This is useful.

It does not capture the history, does it? I was wondering about that, as the "Awards" page is our evidence of when the award was given out and who did it, etc... I was thinking of making a versioned and dated archive and put that on Figshare or Zenodo...

**Comment by zmughal** [comment]
That information is not exposed via the API. [This is all](https://sourceforge.net/rest/p/blueobelisk/bowiki/Blue_Obelisk_Awards) that can be retrieved using the SF Allura API. Getting the history would require web scraping and that wouldn't be too hard to accomplish for the entire wiki in an automated fashion.

Just find out how many versions of the page there are and iterate through them while extracting out the author and revision date.

**Comment by egonw** [comment]
Not done yet, but closing in.

**Comment by egonw** [comment]
OK, I think I'm done with the important stuff. If you find missing pages, please ping me.
